### ISSUE TITLE
black omega website has expired certificate.

### ISSUE THREAD

**Issue by sveinbjornpalsson** [bonezuk/blackomega#5]
Safari didn't want to let me visit it. Said it expired 11 days ago.

Also, it's not visible on google, I don't know if this is why. But the search results point to download aggregators, which always feels like abandonware.

I'm no SEO expert, but I'd also consider updating the copyright year on the website. And maybe see if any of your fans are up for doing the seo thing?

Sv.

**Comment by bonezuk** [comment]
Website has been updated with new certificates.
